import { app, BrowserWindow, ipcMain, dialog } from "electron";
import * as fs from "fs";
import * as path from "path";
import { parse } from "csv-parse";
import sqlite3 from "sqlite3";
import { open } from "sqlite";
import {
  generateAttendanceReport,
  generateCheckinData,
  generateMeetingReport,
  getCurrentAttendance,
  getStatsForDate,
} from "./report";
import { toISOString, getTimestampedFilename, getToday } from "./util";
import {
  disableBluetoothExportDiscovery,
  enableBluetoothExportDiscovery,
  getPairedBluetoothDevices,
  getTrustedBluetoothDevices,
  removeTrustedBluetoothDevice,
  sendFileToBluetoothDevice,
  trustBluetoothDevice,
} from "./bluetooth";
import { ExportDestination, ExportResult } from "./types";

// This allows Typescript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

const DB_PATH = path.join(app.getPath("userData"), "data.db");
const KIOSK_PIN = process.env.ATTENDANCE_KIOSK_PIN || "4561";
const EXPORT_PIN = process.env.ATTENDANCE_EXPORT_PIN || "1654";

(async () => {
  const db = await open({
    filename: DB_PATH,
    driver: sqlite3.cached.Database,
  });
  await db.exec("CREATE TABLE IF NOT EXISTS checkin (timestamp TEXT, idNumber TEXT)");
  await db.exec("CREATE INDEX IF NOT EXISTS timestampIndex ON checkin (timestamp COLLATE NOCASE)");
  await db.exec("CREATE INDEX IF NOT EXISTS idNumberIndex ON checkin (idNumber)");
  await db.exec("CREATE TABLE IF NOT EXISTS student (idNumber TEXT PRIMARY KEY, firstName TEXT, lastName TEXT)");
})();

async function promptForFilePath(defaultFilename: string, title: string) {
  const result = await dialog.showSaveDialog({
    title: title,
    defaultPath: defaultFilename,
    filters: [{ name: "CSV Files", extensions: ["csv"] }],
  });
  if (result.canceled) {
    return null;
  }
  return result.filePath;
}

const createWindow = async () => {
  const db = await open({
    filename: DB_PATH,
    driver: sqlite3.cached.Database,
  });

  // Dynamically calculate the dimensions based on the new --hd command-line flag
  const isHD = process.argv.includes("--hd");
  const viewWidth = isHD ? 1280 : 800;
  const viewHeight = isHD ? 720 : 480;

  // Create the browser window.
  const mainWindow = new BrowserWindow({
    kiosk: process.argv.includes("--kiosk"),
    width: viewWidth,   // Dynamic fallback width if not in kiosk mode
    height: viewHeight, // Dynamic fallback height if not in kiosk mode
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  const trustedBluetoothDevicesPath = path.join(app.getPath("userData"), "trusted-export-devices.json");

  ipcMain.handle("authorizeAdminCode", async (_, pin) => {
    if (pin == KIOSK_PIN) {
      return { success: true, action: "attendance" as const };
    }
    if (EXPORT_PIN && pin == EXPORT_PIN) {
      return { success: true, action: "export" as const };
    }
    return { success: false };
  });

  ipcMain.handle("closeAttendance", async () => {
    try {
      const currentAttendance = await getCurrentAttendance(db, getToday());
      const now = toISOString(new Date());
      for (const attendee of currentAttendance) {
        await db.run(
          "INSERT INTO checkin (timestamp, idNumber) VALUES (?, ?)",
          now,
          attendee.idNumber,
        );
      }
      return { success: true, numClosed: currentAttendance.length };
    } catch (err) {
      dialog.showErrorBox("Error", err.toString());
      return { success: false, numClosed: 0 };
    }
  });

  ipcMain.handle("submit", async (_, idNumber) => {
    try {
      const [, student] = await Promise.all([
        db.run(
          "INSERT INTO checkin (timestamp, idNumber) VALUES (?, ?)",
          toISOString(new Date()),
          idNumber,
        ),
        db.get("SELECT * FROM student WHERE idNumber = ?", idNumber),
      ]);
      const name = student ? `${student.firstName} ${student.lastName}` : null;
      return { success: true, name: name };
    } catch (err) {
      dialog.showErrorBox("Error", err.toString());
      return { success: false };
    }
  });

  ipcMain.handle("getTodaysStats", async () => {
    try {
      return await getStatsForDate(db, getToday());
    } catch (err) {
      dialog.showErrorBox("Error", err.toString());
    }
  });

  ipcMain.handle("getCurrentAttendance", async () => {
    try {
      return await getCurrentAttendance(db, getToday());
    } catch (err) {
      dialog.showErrorBox("Error", err.toString());
      return [];
    }
  });

  async function exportReport(
    data: string,
    filename: string,
    reportName: string,
    destination: ExportDestination,
    bluetoothAddress?: string,
  ): Promise<ExportResult> {
    if (destination === "usb") {
      const filePath = await promptForFilePath(filename, `Export ${reportName}`);
      if (filePath === null) {
        return { success: false, cancelled: true };
      }
      await fs.promises.writeFile(filePath, data);
      return { success: true, message: `${reportName} saved to USB` };
    }
    if (!bluetoothAddress) {
      return { success: false, message: "Select a trusted Bluetooth device" };
    }
    const trustedDevices = await getTrustedBluetoothDevices(trustedBluetoothDevicesPath);
    const device = trustedDevices.find((trustedDevice) => trustedDevice.address === bluetoothAddress);
    if (!device) {
      return { success: false, message: "That Bluetooth device is not trusted for exports" };
    }
    const temporaryFilePath = path.join(app.getPath("temp"), filename);
    await fs.promises.writeFile(temporaryFilePath, data);
    try {
        await sendFileToBluetoothDevice(device, temporaryFilePath);
        return { success: true, message: `${reportName} sent to ${device.name}` };
      } finally {
        await fs.promises.unlink(temporaryFilePath).catch(() => {});
      }
  }

  async function handleReportExport(
    dataPromise: Promise<string>,
    filenamePrefix: string,
    reportName: string,
    destination: ExportDestination,
    bluetoothAddress?: string,
  ): Promise<ExportResult> {
    try {
      const data = await dataPromise;
      const filename = getTimestampedFilename(filenamePrefix, "csv");
      return await exportReport(data, filename, reportName, destination, bluetoothAddress);
    } catch (err) {
      console.log("Report export failed", err);
      return {
        success: false,
        message: err instanceof Error ? err.message : "Report export failed",
      };
    }
  }

  ipcMain.handle("exportAttendanceReport", (_, startDate, endDate, meetingThreshold, destination: ExportDestination, bluetoothAddress?: string) => {
    return handleReportExport(
      generateAttendanceReport(db, startDate, endDate, meetingThreshold),
      "attendance-report",
      "Attendance report",
      destination,
      bluetoothAddress,
    );
  });

  ipcMain.handle("exportMeetingReport", (_, startDate, endDate, meetingThreshold, destination: ExportDestination, bluetoothAddress?: string) => {
    return handleReportExport(
      generateMeetingReport(db, startDate, endDate, meetingThreshold),
      "meeting-report",
      "Meeting report",
      destination,
      bluetoothAddress,
    );
  });

  ipcMain.handle("exportCheckinData", (_, startDate, endDate, meetingThreshold, destination: ExportDestination, bluetoothAddress?: string) => {
    return handleReportExport(
      generateCheckinData(db, startDate, endDate, meetingThreshold),
      "checkins",
      "Check-in data",
      destination,
      bluetoothAddress,
    );
  });

  ipcMain.handle("openBluetoothExport", async () => {
    try {
      await enableBluetoothExportDiscovery();
      return { success: true, message: "Bluetooth is discoverable" };
    } catch (err) {
      return {
        success: false,
        message: err instanceof Error ? err.message : "Could not enable Bluetooth",
      };
    }
  });

  ipcMain.handle("closeBluetoothExport", async () => {
    await disableBluetoothExportDiscovery();
  });

  ipcMain.handle("getPairedBluetoothDevices", async () => {
    return getPairedBluetoothDevices();
  });

  ipcMain.handle("getTrustedBluetoothDevices", async () => {
    return getTrustedBluetoothDevices(trustedBluetoothDevicesPath);
  });

  ipcMain.handle("trustBluetoothDevice", async (_, address: string) => {
    return trustBluetoothDevice(trustedBluetoothDevicesPath, address);
  });

  ipcMain.handle("removeTrustedBluetoothDevice", async (_, address: string) => {
    return removeTrustedBluetoothDevice(trustedBluetoothDevicesPath, address);
  });

  ipcMain.on("importStudents", async () => {
    try {
      const result = await dialog.showOpenDialog({
        title: "Import Students",
        filters: [{ name: "CSV Files", extensions: ["csv"] }],
        properties: ["openFile"],
      });
      if (result.canceled) {
        return;
      }
      const filePath = result.filePaths[0];
      const parser = fs.createReadStream(filePath).pipe(parse({ columns: true }));

      let numSuccess = 0;
      let numFailure = 0;
      await db.run("BEGIN TRANSACTION");
      for await (const record of parser) {
        const idNumber = record.id_number.trim();
        const firstName = record.first_name.trim();
        const lastName = record.last_name.trim();
        if (idNumber.length !== 10 || !firstName || !lastName) {
          numFailure++;
          continue;
        }
        await db.run(
          "INSERT OR REPLACE INTO student (idNumber, firstName, lastName) VALUES (?, ?, ?)",
          idNumber,
          firstName,
          lastName,
        );
        numSuccess++;
      }
      await db.run("COMMIT");
      let message = `${numSuccess} record${numSuccess !== 1 ? "s" : ""} imported successfully;`;
      if (numFailure > 0) {
        message += ` ${numFailure} failed validation`;
      }
      await dialog.showMessageBox(mainWindow, {
        title: "Success",
        message: message,
      });
    } catch (err) {
      dialog.showErrorBox("Error", err.toString());
    }
  });

  // Dynamically updates the content viewport size using the evaluated width and height variables
  mainWindow.setContentSize(viewWidth, viewHeight);
  
  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
};

// This method will be called when Electron has finished initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", createWindow);

app.on("before-quit", () => {
  void disableBluetoothExportDiscovery();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});