import { app, BrowserWindow, ipcMain, dialog } from "electron";
import * as fs from "fs";
import * as path from "path";
import { parse } from "csv-parse";
import { WebClient } from "@slack/web-api";
import { App as SlackApp } from "@slack/bolt";
import sqlite3 from "sqlite3";
import { open, Database } from "sqlite";
import schedule from "node-schedule";
import "dotenv/config";

import {
    generateAttendanceReport,
    generateCheckinData,
    generateMeetingReport,
    getCurrentAttendance,
    getStatsForDate,
    isMeetingDate,
    MEETING_THRESHOLD,
} from "./report";
import { sendReportEmail } from "./email";
import { uploadReportsToSheet } from "./sheets";
import { toISOString, getTimestampedFilename, getToday, getStartDate } from "./util";
import { EnabledActions } from "./types";

// Magic constants auto-generated by Forge's Webpack plugin
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

if (require("electron-squirrel-startup")) {
    app.quit();
}

const DB_PATH = path.join(app.getPath("userData"), "data.db");
const KIOSK_PIN = process.env.ATTENDANCE_KIOSK_PIN || "4561";
const EXPORT_PIN = process.env.ATTENDANCE_EXPORT_PIN || "1654";

let dbInstance: Database | null = null;

async function initDB(): Promise<Database> {
    if (dbInstance) return dbInstance;

    dbInstance = await open({
        filename: DB_PATH,
        driver: sqlite3.cached.Database,
    });

    await dbInstance.exec("CREATE TABLE IF NOT EXISTS checkin (timestamp TEXT, idNumber TEXT)");
    await dbInstance.exec("CREATE INDEX IF NOT EXISTS timestampIndex ON checkin (timestamp COLLATE NOCASE)");
    await dbInstance.exec("CREATE INDEX IF NOT EXISTS idNumberIndex ON checkin (idNumber)");
    await dbInstance.exec("CREATE TABLE IF NOT EXISTS student (idNumber TEXT PRIMARY KEY, firstName TEXT, lastName TEXT, slackId TEXT)");

    try {
        const cols: Array<{ name: string } & Record<string, any>> = await dbInstance.all("PRAGMA table_info(student)");
        const hasSlack = cols.some((c) => c.name === "slackId");
        if (!hasSlack) {
            await dbInstance.exec("ALTER TABLE student ADD COLUMN slackId TEXT");
        }
    } catch (e) {
        console.error("Failed to verify/add slackId column on student table:", e);
    }

    return dbInstance;
}

const enabledActions: EnabledActions = {
    sendToSlack: process.env.SLACK_TOKEN !== undefined && process.env.SLACK_EXPORT_USER_ID !== undefined,
    sendReportEmail: process.env.GMAIL_USER !== undefined && process.env.GMAIL_APP_PASS !== undefined && process.env.REPORT_EMAIL_TO_ADDRESS !== undefined,
    sendToGoogleSheet: process.env.GOOGLE_SHEET_ID !== undefined && process.env.GOOGLE_SERVICE_ACCOUNT_JSON !== undefined,
};

function initSlackBot(db: Database) {
    if (!process.env.SLACK_BOT_TOKEN || !process.env.SLACK_APP_TOKEN) {
        console.log("Slack Bot tokens not configured. Skipping Slack Bot initialization.");
        return;
    }

    const slackBot = new SlackApp({
        token: process.env.SLACK_BOT_TOKEN,
        appToken: process.env.SLACK_APP_TOKEN,
        socketMode: true,
    });

    slackBot.command("/getPeople", async ({ ack, respond }) => {
        await ack();

        try {
            const currentAttendance = await getCurrentAttendance(db, getToday());

            if (currentAttendance.length === 0) {
                await respond({
                    response_type: "in_channel",
                    text: "⚠️ No users are currently checked in.",
                });
                return;
            }

            const now = new Date();
            const nowISO = toISOString(now);

            const attendeeLines = currentAttendance.map((attendee: any) => {
                const checkInTime = new Date(attendee.timestamp);
                const diffMs = now.getTime() - checkInTime.getTime();

                const totalMinutes = Math.floor(diffMs / (1000 * 60));
                const hours = Math.floor(totalMinutes / 60);
                const mins = totalMinutes % 60;

                const timeSpent = hours > 0 ? `${hours}h ${mins}m` : `${mins}m`;
                const fullName = `${attendee.firstName} ${attendee.lastName}`;

                // Append optional Slack handle if present
                const slackHandle = attendee.slackId
                    ? ` (@${attendee.slackId.replace(/^@/, "")})`
                    : "";

                return `• *${fullName}*${slackHandle} — ${timeSpent} (Checked in at ${checkInTime.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })})`;
            });

            // Close attendance in DB
            for (const attendee of currentAttendance) {
                await db.run(
                    "INSERT INTO checkin (timestamp, idNumber) VALUES (?, ?)",
                    nowISO,
                    attendee.idNumber,
                );
            }

            const messageText =
                `📋 *Meeting Attendance Summary*\n` +
                `*Attendance Status:* Closed\n` +
                `*Total Present:* ${currentAttendance.length}\n\n` +
                `*Attendees & Duration:*\n${attendeeLines.join("\n")}`;

            await respond({
                response_type: "in_channel",
                text: messageText,
            });
        } catch (err) {
            console.error("Error executing /getPeople command:", err);
            await respond({
                response_type: "ephemeral",
                text: `❌ Error closing attendance: ${String(err)}`,
            });
        }
    });

    slackBot.start()
        .then(() => console.log("⚡️ Slack Bolt Socket Mode bot is running!"))
        .catch((err) => console.error("Failed to start Slack Bolt bot:", err));
}

function setupCronJobs(db: Database) {
    if (enabledActions.sendReportEmail) {
        schedule.scheduleJob("0 22 * * *", async () => {
            try {
                const today = getToday();
                if (await isMeetingDate(db, today, MEETING_THRESHOLD)) {
                    await sendReportEmail(db);
                    console.log("Report email sent successfully");
                } else {
                    console.log("Not a meeting date, skipping report email");
                }
            } catch (err) {
                console.error("Error sending scheduled report email:", err);
            }
        });
    }

    if (enabledActions.sendToGoogleSheet) {
        schedule.scheduleJob("0 * * * *", async () => {
            try {
                console.log("Running scheduled Google Sheets sync");
                const today = getToday();
                const startDate = getStartDate();
                const checkinData = await generateCheckinData(db, startDate, today, MEETING_THRESHOLD);
                await uploadReportsToSheet(checkinData);
                console.log("Scheduled Google Sheets sync complete");
            } catch (err) {
                console.error("Error during scheduled Google Sheets sync:", err);
            }
        });
    }
}

async function promptForFilePath(defaultFilename: string, title: string) {
    const result = await dialog.showSaveDialog({
        title: title,
        defaultPath: defaultFilename,
        filters: [{ name: "CSV Files", extensions: ["csv"] }],
    });

    if (result.canceled) {
        return null;
    }

    return result.filePath;
}

async function sendReportToSlack(slackClient: WebClient, data: string, filename: string, name: string) {
    const conversation = await slackClient.conversations.open({
        users: process.env.SLACK_EXPORT_USER_ID || "",
    });
    await slackClient.filesUploadV2({
        channel_id: conversation.channel?.id || "",
        initial_comment: `${name} exported by attendance kiosk`,
        file: Buffer.from(data, "utf-8"),
        filename: filename,
    });
}

const createWindow = async (db: Database) => {
    const mainWindow = new BrowserWindow({
        kiosk: process.argv.includes("--kiosk"),
        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
        },
    });

    const slackClient = new WebClient(process.env.SLACK_TOKEN);

    ipcMain.removeHandler("authorizeAdminCode");
    ipcMain.handle("authorizeAdminCode", async (_, pin) => {
        if (pin === KIOSK_PIN) {
            return { success: true, action: "attendance" as const };
        }
        if (EXPORT_PIN && pin === EXPORT_PIN) {
            return { success: true, action: "export" as const };
        }
        return { success: false };
    });

    ipcMain.removeHandler("closeAttendance");
    ipcMain.handle("closeAttendance", async () => {
        try {
            const currentAttendance = await getCurrentAttendance(db, getToday());
            const now = toISOString(new Date());

            // Fast DB operations
            for (const attendee of currentAttendance) {
                await db.run(
                    "INSERT INTO checkin (timestamp, idNumber) VALUES (?, ?)",
                    now,
                    attendee.idNumber,
                );
            }

            // Asynchronous email delivery (non-blocking)
            if (enabledActions.sendReportEmail) {
                sendReportEmail(db)
                    .then(() => console.log("Attendance close email sent successfully"))
                    .catch((emailErr) => console.error("Failed to send attendance close email:", emailErr));
            }

            // Return immediately to display the banner without delay
            return { success: true, numClosed: currentAttendance.length, emailed: true };
        } catch (err) {
            dialog.showErrorBox("Error", String(err));
            return { success: false, numClosed: 0, emailed: false };
        }
    });

    ipcMain.removeHandler("submit");
    ipcMain.handle("submit", async (_, idNumber) => {
        const trimmedInput = idNumber?.trim();

        // Intercept Admin / Export PINs
        if (trimmedInput === KIOSK_PIN) {
            return { success: true, action: "attendance" as const };
        }
        if (EXPORT_PIN && trimmedInput === EXPORT_PIN) {
            return { success: true, action: "export" as const };
        }

        try {
            const student = await db.get(
                "SELECT * FROM student WHERE idNumber = ?",
                trimmedInput,
            );

            if (!student) {
                return { success: false, reason: "user_not_found" };
            }

            await db.run(
                "INSERT INTO checkin (timestamp, idNumber) VALUES (?, ?)",
                toISOString(new Date()),
                trimmedInput,
            );

            const name = `${student.firstName} ${student.lastName}`;
            return { success: true, action: "checkin" as const, name: name };
        } catch (err) {
            dialog.showErrorBox("Error", String(err));
            return { success: false };
        }
    });

    ipcMain.removeHandler("getTodaysStats");
    ipcMain.handle("getTodaysStats", async () => {
        try {
            return await getStatsForDate(db, getToday());
        } catch (err) {
            dialog.showErrorBox("Error", String(err));
        }
    });

    ipcMain.removeHandler("getCurrentAttendance");
    ipcMain.handle("getCurrentAttendance", async () => {
        try {
            return await getCurrentAttendance(db, getToday());
        } catch (err) {
            dialog.showErrorBox("Error", String(err));
            return [];
        }
    });

    ipcMain.removeHandler("getEnabledActions");
    ipcMain.handle("getEnabledActions", async () => {
        return enabledActions;
    });

    ipcMain.removeHandler("getStudentIds");
    ipcMain.handle("getStudentIds", async () => {
        const rows = await db.all("SELECT idNumber FROM student ORDER BY idNumber");
        return rows.map((row: { idNumber: string }) => row.idNumber);
    });

    ipcMain.on("syncToGoogleSheet", async () => {
    console.log("--- GOOGLE SHEETS SYNC TRIGGERED ---");
    console.log("sendToGoogleSheet enabled?", enabledActions.sendToGoogleSheet);
    console.log("GOOGLE_SHEET_ID present?", !!process.env.GOOGLE_SHEET_ID);
    console.log("GOOGLE_SERVICE_ACCOUNT_JSON present?", !!process.env.GOOGLE_SERVICE_ACCOUNT_JSON);

    if (!enabledActions.sendToGoogleSheet) {
        dialog.showErrorBox("Not Configured", "Google Sheets sync is not configured on this device.");
        return;
    }

    try {
        const startDate = getStartDate();
        const today = getToday();
        console.log("Fetching check-in data from", startDate, "to", today);

        const checkinData = await generateCheckinData(db, startDate, today, MEETING_THRESHOLD);
        console.log("Data returned from DB:", checkinData);

        await uploadReportsToSheet(checkinData);
        console.log("Sync complete!");
        
        await dialog.showMessageBox(mainWindow, { title: "Success", message: "Reports synced to Google Sheets" });
    } catch (err) {
        console.error("Sync error:", err);
        dialog.showErrorBox("Error", String(err));
    }
});

    ipcMain.on("exportAttendanceReport", async (_, startDate, endDate, meetingThreshold, sendToSlack) => {
        try {
            const filename = getTimestampedFilename("attendance-report", "csv");
            const filePath = sendToSlack ? null : await promptForFilePath(filename, "Export Attendance Report");

            if (!sendToSlack && filePath === null) {
                return;
            }

            const data = await generateAttendanceReport(db, startDate, endDate, meetingThreshold);

            if (sendToSlack) {
                await sendReportToSlack(slackClient, data, filename, "Attendance report");
            } else {
                await fs.promises.writeFile(filePath!, data);
            }

            await dialog.showMessageBox(mainWindow, {
                title: "Success",
                message: "Attendance report exported successfully",
            });
        } catch (err) {
            dialog.showErrorBox("Error", String(err));
        }
    });

    ipcMain.on("exportMeetingReport", async (_, startDate, endDate, meetingThreshold, sendToSlack) => {
        try {
            const filename = getTimestampedFilename("meeting-report", "csv");
            const filePath = sendToSlack ? null : await promptForFilePath(filename, "Export Meeting Report");

            if (!sendToSlack && filePath === null) {
                return;
            }

            const data = await generateMeetingReport(db, startDate, endDate, meetingThreshold);

            if (sendToSlack) {
                await sendReportToSlack(slackClient, data, filename, "Meeting report");
            } else {
                await fs.promises.writeFile(filePath!, data);
            }

            await dialog.showMessageBox(mainWindow, {
                title: "Success",
                message: "Meeting report exported successfully",
            });
        } catch (err) {
            dialog.showErrorBox("Error", String(err));
        }
    });

    ipcMain.on("exportCheckinData", async (_, startDate, endDate, meetingThreshold, sendToSlack) => {
        try {
            const filename = getTimestampedFilename("checkins", "csv");
            const filePath = sendToSlack ? null : await promptForFilePath(filename, "Export Check in Data");

            if (!sendToSlack && filePath === null) {
                return;
            }

            const data = await generateCheckinData(db, startDate, endDate, meetingThreshold);

            if (sendToSlack) {
                await sendReportToSlack(slackClient, data, filename, "Check in Data");
            } else {
                await fs.promises.writeFile(filePath!, data);
            }

            await dialog.showMessageBox(mainWindow, {
                title: "Success",
                message: "Check in data exported successfully",
            });
        } catch (err) {
            dialog.showErrorBox("Error", String(err));
        }
    });

    ipcMain.on("importStudents", async () => {
        try {
            const result = await dialog.showOpenDialog({
                title: "Import Students",
                filters: [{ name: "CSV Files", extensions: ["csv"] }],
                properties: ["openFile"],
            });

            if (result.canceled) {
                return;
            }

            const filePath = result.filePaths[0];
            const parser = fs
                .createReadStream(filePath)
                .pipe(parse({ columns: true })) as unknown as AsyncIterable<Record<string, string>>;

            let numSuccess = 0;
            let numFailure = 0;

            await db.run("BEGIN TRANSACTION");
            try {
                for await (const record of parser) {
                    const idNumber = (record.id_number || record.idNumber)?.trim();
                    const firstName = (record.first_name || record.firstName)?.trim();
                    const lastName = (record.last_name || record.lastName)?.trim();
                    const slackId = (
                        record.slack_id ||
                        record.slackId ||
                        record.slackid ||
                        record.slackUsername ||
                        record.slack_username
                    )?.trim() || null;

                    if (!idNumber || idNumber.length !== 10 || !firstName || !lastName) {
                        numFailure++;
                        continue;
                    }

                    await db.run(
                        "INSERT OR REPLACE INTO student (idNumber, firstName, lastName, slackId) VALUES (?, ?, ?, ?)",
                        idNumber,
                        firstName,
                        lastName,
                        slackId,
                    );
                    numSuccess++;
                }
                await db.run("COMMIT");
            } catch (streamErr) {
                await db.run("ROLLBACK");
                throw streamErr;
            }

            let message = `${numSuccess} record${numSuccess !== 1 ? "s" : ""} imported successfully`;
            if (numFailure > 0) {
                message += ` (${numFailure} failed validation)`;
            }
            await dialog.showMessageBox(mainWindow, {
                title: "Success",
                message: message,
            });
        } catch (err) {
            dialog.showErrorBox("Error", String(err));
        }
    });

    ipcMain.on("sendReportEmail", async (_, reportType?: "attendance" | "meeting" | "checkin" | "all") => {
        try {
            await sendReportEmail(db, reportType);
            await dialog.showMessageBox(mainWindow, {
                title: "Success",
                message: "Report email sent successfully",
            });
        } catch (err) {
            dialog.showErrorBox("Error", String(err));
        }
    });

    mainWindow.setContentSize(800, 480);
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
};

// Lifecycle Handlers
app.on("ready", async () => {
    const db = await initDB();
    setupCronJobs(db);
    initSlackBot(db);
    await createWindow(db);
});

app.on("window-all-closed", () => {
    if (process.platform !== "darwin") {
        app.quit();
    }
});

app.on("activate", async () => {
    if (BrowserWindow.getAllWindows().length === 0) {
        const db = await initDB();
        await createWindow(db);
    }
});