import { app, BrowserWindow, ipcMain, dialog } from "electron";
import * as fs from "fs";
import * as path from "path";
import { parse } from "csv-parse";
import { WebClient } from "@slack/web-api";
import sqlite3 from "sqlite3";
import { open, Database } from "sqlite";
import schedule from "node-schedule";
import "dotenv/config"; 

import {
    generateAttendanceReport,
    generateCheckinData,
    generateMeetingReport,
    getCurrentAttendance,
    getStatsForDate,
    isMeetingDate,
    MEETING_THRESHOLD,
} from "./report";
import { sendReportEmail } from "./email";
import { uploadReportsToSheet } from "./sheets";
import { toISOString, getTimestampedFilename, getToday, getStartDate } from "./util";
import { EnabledActions } from "./types";

// This allows TypeScript to pick up the magic constants auto-generated by Forge's Webpack plugin
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
    app.quit();
}

const DB_PATH = path.join(app.getPath("userData"), "data.db");
const KIOSK_PIN = process.env.ATTENDANCE_KIOSK_PIN || "4561";
const EXPORT_PIN = process.env.ATTENDANCE_EXPORT_PIN || "1654";

let dbInstance: Database | null = null;

async function initDB(): Promise<Database> {
    if (dbInstance) return dbInstance;

    dbInstance = await open({
        filename: DB_PATH,
        driver: sqlite3.cached.Database,
    });

    await dbInstance.exec("CREATE TABLE IF NOT EXISTS checkin (timestamp TEXT, idNumber TEXT)");
    await dbInstance.exec("CREATE INDEX IF NOT EXISTS timestampIndex ON checkin (timestamp COLLATE NOCASE)");
    await dbInstance.exec("CREATE INDEX IF NOT EXISTS idNumberIndex ON checkin (idNumber)");
    await dbInstance.exec("CREATE TABLE IF NOT EXISTS student (idNumber TEXT PRIMARY KEY, firstName TEXT, lastName TEXT, slackId TEXT)");

    // Ensure legacy DBs get the optional slackId column added if it didn't exist previously
    try {
        const cols: Array<{ name: string } & Record<string, any>> = await dbInstance.all("PRAGMA table_info(student)");
        const hasSlack = cols.some((c) => c.name === "slackId");
        if (!hasSlack) {
            await dbInstance.exec("ALTER TABLE student ADD COLUMN slackId TEXT");
        }
    } catch (e) {
        // If migration check fails, log and continue — the app can still function without the column
        console.error("Failed to verify/add slackId column on student table:", e);
    }

    return dbInstance;
}

const enabledActions: EnabledActions = {
    sendToSlack: process.env.SLACK_TOKEN !== undefined && process.env.SLACK_EXPORT_USER_ID !== undefined,
    // Use Nodemailer (Gmail) for report email delivery. Require Gmail credentials and a destination address.
    sendReportEmail: process.env.GMAIL_USER !== undefined && process.env.GMAIL_APP_PASS !== undefined && process.env.REPORT_EMAIL_TO_ADDRESS !== undefined,
    sendToGoogleSheet: process.env.GOOGLE_SHEET_ID !== undefined && process.env.GOOGLE_SERVICE_ACCOUNT_JSON !== undefined,
};

function setupCronJobs(db: Database) {
    if (enabledActions.sendReportEmail) {
        schedule.scheduleJob("0 22 * * *", async () => {
            try {
                const today = getToday();
                if (await isMeetingDate(db, today, MEETING_THRESHOLD)) {
                    await sendReportEmail(db);
                    console.log("Report email sent successfully");
                } else {
                    console.log("Not a meeting date, skipping report email");
                }
            } catch (err) {
                console.error("Error sending scheduled report email:", err);
            }
        });
    }

    // Auto-sync to Google Sheets every hour if enabled
    if (enabledActions.sendToGoogleSheet) {
        schedule.scheduleJob("0 * * * *", async () => {
            try {
                console.log("Running scheduled Google Sheets sync");
                const today = getToday();
                const startDate = getStartDate();
                const checkinData = await generateCheckinData(db, startDate, today, MEETING_THRESHOLD);
                await uploadReportsToSheet(checkinData);
                console.log("Scheduled Google Sheets sync complete");
            } catch (err) {
                console.error("Error during scheduled Google Sheets sync:", err);
            }
        });
    }
}

async function promptForFilePath(defaultFilename: string, title: string) {
    const result = await dialog.showSaveDialog({
        title: title,
        defaultPath: defaultFilename,
        filters: [{ name: "CSV Files", extensions: ["csv"] }],
    });

    if (result.canceled) {
        return null;
    }

    return result.filePath;
}

async function sendReportToSlack(slackClient: WebClient, data: string, filename: string, name: string) {
    const conversation = await slackClient.conversations.open({
        users: process.env.SLACK_EXPORT_USER_ID || "",
    });
    await slackClient.filesUploadV2({
        channel_id: conversation.channel?.id || "",
        initial_comment: `${name} exported by attendance kiosk`,
        file: Buffer.from(data, "utf-8"),
        filename: filename,
    });
}

const createWindow = async (db: Database) => {
    const mainWindow = new BrowserWindow({
        kiosk: process.argv.includes("--kiosk"),
        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
        },
    });

    const slackClient = new WebClient(process.env.SLACK_TOKEN);

    ipcMain.removeHandler("authorizeAdminCode");
    ipcMain.handle("authorizeAdminCode", async (_, pin) => {
        if (pin === KIOSK_PIN) {
            return { success: true, action: "attendance" as const };
        }
        if (EXPORT_PIN && pin === EXPORT_PIN) {
            return { success: true, action: "export" as const };
        }
        return { success: false };
    });

    ipcMain.removeHandler("closeAttendance");
    ipcMain.handle("closeAttendance", async () => {
        try {
            const currentAttendance = await getCurrentAttendance(db, getToday());
            const now = toISOString(new Date());
            for (const attendee of currentAttendance) {
                await db.run(
                    "INSERT INTO checkin (timestamp, idNumber) VALUES (?, ?)",
                    now,
                    attendee.idNumber,
                );
            }

            let emailed = false;
            if (enabledActions.sendReportEmail) {
                try {
                    await sendReportEmail(db);
                    emailed = true;
                } catch (emailErr) {
                    console.error("Failed to send attendance close email", emailErr);
                }
            }

            return { success: true, numClosed: currentAttendance.length, emailed };
        } catch (err) {
            dialog.showErrorBox("Error", String(err));
            return { success: false, numClosed: 0, emailed: false };
        }
    });

    ipcMain.removeHandler("submit");
    ipcMain.handle("submit", async (_, idNumber) => {
        try {
            const [, student] = await Promise.all([
                db.run(
                    "INSERT INTO checkin (timestamp, idNumber) VALUES (?, ?)",
                    toISOString(new Date()),
                    idNumber,
                ),
                db.get(
                    "SELECT * FROM student WHERE idNumber = ?",
                    idNumber,
                ),
            ]);
            const name = student ? `${student.firstName} ${student.lastName}` : null;
            return { success: true, name: name };
        } catch (err) {
            dialog.showErrorBox("Error", String(err));
            return { success: false };
        }
    });

    ipcMain.removeHandler("getTodaysStats");
    ipcMain.handle("getTodaysStats", async () => {
        try {
            return await getStatsForDate(db, getToday());
        } catch (err) {
            dialog.showErrorBox("Error", String(err));
        }
    });

    ipcMain.removeHandler("getCurrentAttendance");
    ipcMain.handle("getCurrentAttendance", async () => {
        try {
            return await getCurrentAttendance(db, getToday());
        } catch (err) {
            dialog.showErrorBox("Error", String(err));
            return [];
        }
    });

    ipcMain.removeHandler("getEnabledActions");
    ipcMain.handle("getEnabledActions", async () => {
        return enabledActions;
    });

    ipcMain.removeHandler("getStudentIds");
    ipcMain.handle("getStudentIds", async () => {
        const rows = await db.all("SELECT idNumber FROM student ORDER BY idNumber");
        return rows.map((row: { idNumber: string }) => row.idNumber);
    });

    // Sync to Google Sheets on-demand from renderer
    ipcMain.removeAllListeners("syncToGoogleSheet");
    ipcMain.on("syncToGoogleSheet", async () => {
        if (!enabledActions.sendToGoogleSheet) {
            dialog.showErrorBox("Not Configured", "Google Sheets sync is not configured on this device.");
            return;
        }

        try {
            const startDate = getStartDate();
            const today = getToday();
            const checkinData = await generateCheckinData(db, startDate, today, MEETING_THRESHOLD);
            await uploadReportsToSheet(checkinData);
            await dialog.showMessageBox(mainWindow, { title: "Success", message: "Reports synced to Google Sheets" });
        } catch (err) {
            console.error("Failed to sync reports to Google Sheets:", err);
            dialog.showErrorBox("Error", String(err));
        }
    });

    ipcMain.on("exportAttendanceReport", async (_, startDate, endDate, meetingThreshold, sendToSlack) => {
        try {
            const filename = getTimestampedFilename("attendance-report", "csv");
            const filePath = sendToSlack ? null : await promptForFilePath(filename, "Export Attendance Report");

            if (!sendToSlack && filePath === null) {
                return;
            }

            const data = await generateAttendanceReport(db, startDate, endDate, meetingThreshold);

            if (sendToSlack) {
                await sendReportToSlack(slackClient, data, filename, "Attendance report");
            } else {
                await fs.promises.writeFile(filePath!, data);
            }

            await dialog.showMessageBox(mainWindow, {
                title: "Success",
                message: "Attendance report exported successfully",
            });
        } catch (err) {
            dialog.showErrorBox("Error", String(err));
        }
    });

    ipcMain.on("exportMeetingReport", async (_, startDate, endDate, meetingThreshold, sendToSlack) => {
        try {
            const filename = getTimestampedFilename("meeting-report", "csv");
            const filePath = sendToSlack ? null : await promptForFilePath(filename, "Export Meeting Report");

            if (!sendToSlack && filePath === null) {
                return;
            }

            const data = await generateMeetingReport(db, startDate, endDate, meetingThreshold);

            if (sendToSlack) {
                await sendReportToSlack(slackClient, data, filename, "Meeting report");
            } else {
                await fs.promises.writeFile(filePath!, data);
            }

            await dialog.showMessageBox(mainWindow, {
                title: "Success",
                message: "Meeting report exported successfully",
            });
        } catch (err) {
            dialog.showErrorBox("Error", String(err));
        }
    });

    ipcMain.on("exportCheckinData", async (_, startDate, endDate, meetingThreshold, sendToSlack) => {
        try {
            const filename = getTimestampedFilename("checkins", "csv");
            const filePath = sendToSlack ? null : await promptForFilePath(filename, "Export Check in Data");

            if (!sendToSlack && filePath === null) {
                return;
            }

            const data = await generateCheckinData(db, startDate, endDate, meetingThreshold);

            if (sendToSlack) {
                await sendReportToSlack(slackClient, data, filename, "Check in Data");
            } else {
                await fs.promises.writeFile(filePath!, data);
            }

            await dialog.showMessageBox(mainWindow, {
                title: "Success",
                message: "Check in data exported successfully",
            });
        } catch (err) {
            dialog.showErrorBox("Error", String(err));
        }
    });
    ipcMain.on("importStudents", async () => {
        try {
            const result = await dialog.showOpenDialog({
                title: "Import Students",
                filters: [{ name: "CSV Files", extensions: ["csv"] }],
                properties: ["openFile"],
            });

            if (result.canceled) {
                return;
            }

            const filePath = result.filePaths[0];
            // Cast the stream to AsyncIterable to fix the TypeScript 'next()' error
            const parser = fs
                .createReadStream(filePath)
                .pipe(parse({ columns: true })) as AsyncIterable<Record<string, string>>;

            let numSuccess = 0;
            let numFailure = 0;

            await db.run("BEGIN TRANSACTION");
            try {
                for await (const record of parser) {
                    const idNumber = record.id_number?.trim();
                    const firstName = record.first_name?.trim();
                    const lastName = record.last_name?.trim();
                    // Optional Slack ID column: accept slack_id or slackId (case-sensitive depending on CSV headers)
                    const slackId = (record.slack_id || record.slackId || record.slackid)?.trim() || null;

                    if (!idNumber || idNumber.length !== 10 || !firstName || !lastName) {
                        numFailure++;
                        continue;
                    }

                    await db.run(
                        "INSERT OR REPLACE INTO student (idNumber, firstName, lastName, slackId) VALUES (?, ?, ?, ?)",
                        idNumber,
                        firstName,
                        lastName,
                        slackId,
                    );
                    numSuccess++;
                }
                await db.run("COMMIT");
            } catch (streamErr) {
                await db.run("ROLLBACK");
                throw streamErr;
            }

            let message = `${numSuccess} record${numSuccess !== 1 ? "s" : ""} imported successfully`;
            if (numFailure > 0) {
                message += ` (${numFailure} failed validation)`;
            }
            await dialog.showMessageBox(mainWindow, {
                title: "Success",
                message: message,
            });
        } catch (err) {
            dialog.showErrorBox("Error", String(err));
        }
    });
    ipcMain.on("sendReportEmail", async (_, reportType?: "attendance" | "meeting" | "checkin" | "all") => {
        try {
            await sendReportEmail(db, reportType);
            await dialog.showMessageBox(mainWindow, {
                title: "Success",
                message: "Report email sent successfully",
            });
        } catch (err) {
            dialog.showErrorBox("Error", String(err));
        }
    });

    mainWindow.setContentSize(800, 480);
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
};

// Lifecycle Handlers
app.on("ready", async () => {
    const db = await initDB();
    setupCronJobs(db);
    await createWindow(db);
});

app.on("window-all-closed", () => {
    if (process.platform !== "darwin") {
        app.quit();
    }
});

app.on("activate", async () => {
    if (BrowserWindow.getAllWindows().length === 0) {
        const db = await initDB();
        await createWindow(db);
    }
});